afk_timeout: 60
autohide_substrings:
- C:\
autosave_interval: 60
button_width: 20
categories:
- Productivity
- Entertainment
- Social
- Miscellaneous
colors:
  active: '#55ff55'
  afk: '#55a0ff'
  entertainment: '#8888ff'
  idle: '#ff7777'
  miscellaneous: '#aaaaaa'
  productivity: '#ff8888'
  social: '#88ff88'
  text: '#000000'
  unselected: '#dddddd'
default_category: Miscellaneous
label_font: Calibri 24
label_font_mini: Calibri 16
update_interval: 1
